name: Publish Docker image
on:
  push:
    branches: master
jobs:
  push_to_registry:
    name: Push Nginx image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [php, proxy]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          workdir: ./${{ matrix.image }}
          tags: somosyampi/docker-nginx-alpine:${{ matrix.image }}
          tag_with_ref: true